name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: python3 -m pip install mypy pylint
      - name: Check-out
        uses: actions/checkout@v4
      - name: Check
        run: ${{github.workspace}}/ci/check.sh
