name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: python3 -m pip install mypy pylint
      - name: Check-out
        uses: actions/checkout@v4
      - name: Lint
        run: ${{github.workspace}}/ci/check.sh
      - name: Regression Test
        run: ${{github.workspace}}/test/regression-test.sh
